services:
  sqlite.n8n.lan:
    container_name: n8n-sqlite
    image: local/n8nio/n8n:1
    restart: always
    dns: [1.1.1.1, 8.8.8.8]
    network_mode: bridge
    ports: ["127.0.0.1:5678:5678"]
    volumes:
    - ./data/bin:/home/node/apps/bin
    - ./data/n8n_data:/home/node/.n8n
    - ./data/n8n_workspace:/home/node/workspace
    environment:
      TZ: Asia/Shanghai
      GENERIC_TIMEZONE: Asia/Shanghai
      DB_SQLITE_POOL_SIZE: "8"
      N8N_RUNNERS_ENABLED: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
      #NODES_EXCLUDE: "[\"n8n-nodes-base.executeCommand\", \"n8n-nodes-base.readWriteFile\"]"
      NODES_EXCLUDE: "[]"
      N8N_SECURE_COOKIE: "false" # development
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: "5432"
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: your_password
      DB_POSTGRESDB_DATABASE: n8n
      WEBHOOK_URL: https://domain.test
      https_proxy: socks5h://172.17.0.1:1080
      no_proxy: localhost,127.0.0.1,172.17.0.1
