networks:
  net: { name: gitea, driver: bridge, external: false }

services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    restart: always
    user: ${USER_UID}:${USER_GID}
    networks: [net]
    # network_mode: bridge
    ports: ["3011:3000", "3012:22"]
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./data/gitea:/data
