networks:
  net: { name: "gitea", driver: bridge, external: false }

services:
  gitea:
    image: gitea/gitea:1
    restart: always
    user: ${USER_UID}:${USER_GID}
    networks: [net]
    depends_on: ["postgres"]
    container_name: gitea
    ports: ["${HTTP_Port}:3000", "${SSH_Port}:22"]
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      GITEA__database__DB_TYPE: postgres
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./data/gitea:/data

  postgres:
    image: postgres:17-alpine
    restart: always
    networks: ["net"]
    container_name: postgres
    environment:
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
      POSTGRES_USER: gitea
      POSTGRES_DB: gitea
    #  POSTGRES_PASSWORD: gitea
    env_file: [./configs/gitea.env]
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
