services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    network_mode: bridge
    ports:
    # <Host Port>:<Container Port>
    - "127.0.0.1:3001:3001"
    volumes:
    - ./data/uptime-kuma:/app/data
