#networks:
#  net: { name: alpine, driver: bridge, external: false }

services:
  alpine:
    image: local/alpine:3
    network_mode: host
    #networks: ["net"]
    #ports: [8080:8080]
    hostname: alpine
    container_name: alpine
    volumes:
    - ./data:/home/appuser/workspace
    environment:
      TZ: Asia/Shanghai
    working_dir: /home/appuser/workspace
    command: [tail, -f, /etc/hosts]
